import { requireAdmin } from '@/lib/require-admin'
import { renderCampaignPdf, renderCampaignDocx } from '@/lib/campaign-export'

// GET /api/admin/campaigns/[id]/export?format=pdf|docx
// Renders the campaign's saved plan on-demand — never re-generated by AI,
// always reflects the latest saved state.
export async function GET(req, { params }) {
  const auth = await requireAdmin()
  if (auth.error) return Response.json({ error: auth.error }, { status: auth.status })

  const { id } = await params
  const { searchParams } = new URL(req.url)
  const format = searchParams.get('format')
  if (!['pdf', 'docx'].includes(format)) {
    return Response.json({ error: 'format must be pdf or docx' }, { status: 400 })
  }

  const { data: campaign, error } = await auth.admin
    .from('campaigns')
    .select('name, budget_thb, period_start, period_end, plan')
    .eq('id', id)
    .single()
  if (error || !campaign) return Response.json({ error: 'Campaign not found' }, { status: 404 })

  const safeName = campaign.name.replace(/[^a-z0-9]+/gi, '-').toLowerCase().slice(0, 60)

  if (format === 'pdf') {
    const buffer = await renderCampaignPdf(campaign)
    return new Response(buffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${safeName}.pdf"`,
      },
    })
  }

  const buffer = await renderCampaignDocx(campaign)
  return new Response(buffer, {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${safeName}.docx"`,
    },
  })
}
