// Renders a saved campaign plan into a downloadable PDF or Word (.docx) file
// for handing off to an implementation team. Both are built on-demand from
// the stored `plan` JSON — never re-generated by AI, never cached as a file,
// so they always reflect the campaign's current saved state.
import React from 'react'
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer'
import { Document as DocxDocument, Packer, Paragraph, HeadingLevel, TextRun, Table, TableRow, TableCell, WidthType } from 'docx'

const BRAND_GREEN = '#3B5249'
const BRAND_GOLD = '#C4924A'

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: 'Helvetica' },
  title: { fontSize: 20, marginBottom: 4, color: BRAND_GREEN },
  subtitle: { fontSize: 11, marginBottom: 16, color: '#6B6663' },
  sectionTitle: { fontSize: 13, marginTop: 16, marginBottom: 6, color: BRAND_GREEN, fontWeight: 700 },
  item: { marginBottom: 8, paddingBottom: 8, borderBottom: '1pt solid #E0D9D0' },
  itemTitle: { fontSize: 11, fontWeight: 700, marginBottom: 2 },
  itemBody: { fontSize: 10, color: '#4A4745', lineHeight: 1.4 },
  itemMeta: { fontSize: 9, color: BRAND_GOLD, marginTop: 2 },
  row: { flexDirection: 'row', marginBottom: 4 },
  cell: { flex: 1, fontSize: 9, paddingRight: 6 },
})

function PdfDocument({ campaign }) {
  const p = campaign.plan
  return (
    React.createElement(Document, null,
      React.createElement(Page, { size: 'A4', style: styles.page },
        React.createElement(Text, { style: styles.title }, campaign.name),
        React.createElement(Text, { style: styles.subtitle }, `${campaign.period_start} — ${campaign.period_end}${campaign.budget_thb ? ` · Budget ฿${Number(campaign.budget_thb).toLocaleString()}` : ''}`),

        p.bigIdea && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'Big Idea'),
          React.createElement(Text, { style: styles.itemTitle }, p.bigIdea.title),
          React.createElement(Text, { style: styles.itemBody }, p.bigIdea.rationale)
        ),

        p.campaignIdeas?.length > 0 && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'Alternate Ideas'),
          ...p.campaignIdeas.map((c, i) => React.createElement(View, { key: i, style: styles.item },
            React.createElement(Text, { style: styles.itemTitle }, `${c.name} — "${c.tagline}"`),
            React.createElement(Text, { style: styles.itemBody }, c.theme),
            React.createElement(Text, { style: styles.itemMeta }, c.whyItFits)
          ))
        ),

        p.channelPlan?.length > 0 && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'Channel Plan & Budget'),
          ...p.channelPlan.map((c, i) => React.createElement(View, { key: i, style: styles.item },
            React.createElement(Text, { style: styles.itemTitle }, `${c.channel} — ฿${Number(c.budgetTHB ?? 0).toLocaleString()}`),
            React.createElement(Text, { style: styles.itemBody }, `${c.role}. ${c.rationale}`)
          ))
        ),

        p.timeline?.length > 0 && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'Timeline'),
          ...p.timeline.map((t, i) => React.createElement(View, { key: i, style: styles.item },
            React.createElement(Text, { style: styles.itemTitle }, `${t.phase} (Day ${t.startOffset}–${t.startOffset + t.durationDays})`),
            React.createElement(Text, { style: styles.itemBody }, (t.activities ?? []).join(' · '))
          ))
        ),

        p.messagingPillars?.length > 0 && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'Messaging Pillars'),
          ...p.messagingPillars.map((m, i) => React.createElement(View, { key: i, style: styles.item },
            React.createElement(Text, { style: styles.itemTitle }, m.pillar),
            React.createElement(Text, { style: styles.itemBody }, m.description),
            React.createElement(Text, { style: styles.itemMeta }, m.proofPoint)
          ))
        ),

        p.taglines?.length > 0 && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'Tagline Options'),
          React.createElement(Text, { style: styles.itemBody }, p.taglines.join('   •   '))
        ),

        p.audiencePersonas?.length > 0 && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'Audience Personas'),
          ...p.audiencePersonas.map((a, i) => React.createElement(View, { key: i, style: styles.item },
            React.createElement(Text, { style: styles.itemTitle }, a.name),
            React.createElement(Text, { style: styles.itemBody }, `${a.profile} Motivation: ${a.motivation}`),
            React.createElement(Text, { style: styles.itemMeta }, `Best channel: ${a.bestChannel}`)
          ))
        ),

        p.contentCalendar?.length > 0 && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'Content Calendar'),
          ...p.contentCalendar.map((c, i) => React.createElement(View, { key: i, style: styles.item },
            React.createElement(Text, { style: styles.itemTitle }, `Week ${c.week} — ${c.channel} (${c.contentType})`),
            React.createElement(Text, { style: styles.itemBody }, c.description)
          ))
        ),

        p.journeyMap?.length > 0 && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'Customer Journey Map'),
          ...p.journeyMap.map((j, i) => React.createElement(View, { key: i, style: styles.item },
            React.createElement(Text, { style: styles.itemTitle }, `${j.stage} — ${j.touchpoint}`),
            React.createElement(Text, { style: styles.itemBody }, j.content),
            React.createElement(Text, { style: styles.itemMeta }, `Leakage risk: ${j.leakageRisk}`)
          ))
        ),

        p.kpis?.length > 0 && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'KPIs'),
          ...p.kpis.map((k, i) => React.createElement(View, { key: i, style: styles.item },
            React.createElement(Text, { style: styles.itemTitle }, `${k.metric}: ${k.target}`),
            React.createElement(Text, { style: styles.itemBody }, k.howToMeasure)
          ))
        ),

        p.preMortem?.length > 0 && React.createElement(View, null,
          React.createElement(Text, { style: styles.sectionTitle }, 'Pre-Mortem — What Could Go Wrong'),
          ...p.preMortem.map((r, i) => React.createElement(View, { key: i, style: styles.item },
            React.createElement(Text, { style: styles.itemTitle }, `${r.risk} (${r.likelihood})`),
            React.createElement(Text, { style: styles.itemBody }, r.mitigation)
          ))
        )
      )
    )
  )
}

export async function renderCampaignPdf(campaign) {
  return renderToBuffer(React.createElement(PdfDocument, { campaign }))
}

// ── Word (.docx) ────────────────────────────────────────────────────────
function heading(text) {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 120 } })
}
function bodyPara(text, opts = {}) {
  return new Paragraph({ children: [new TextRun({ text, ...opts })], spacing: { after: 100 } })
}
function itemTitlePara(text) {
  return new Paragraph({ children: [new TextRun({ text, bold: true })], spacing: { after: 40 } })
}

export async function renderCampaignDocx(campaign) {
  const p = campaign.plan
  const children = [
    new Paragraph({ text: campaign.name, heading: HeadingLevel.TITLE }),
    bodyPara(`${campaign.period_start} — ${campaign.period_end}${campaign.budget_thb ? ` · Budget ฿${Number(campaign.budget_thb).toLocaleString()}` : ''}`, { color: '6B6663' }),
  ]

  if (p.bigIdea) {
    children.push(heading('Big Idea'))
    children.push(itemTitlePara(p.bigIdea.title))
    children.push(bodyPara(p.bigIdea.rationale))
  }

  if (p.campaignIdeas?.length) {
    children.push(heading('Alternate Ideas'))
    for (const c of p.campaignIdeas) {
      children.push(itemTitlePara(`${c.name} — "${c.tagline}"`))
      children.push(bodyPara(c.theme))
      children.push(bodyPara(c.whyItFits, { italics: true, color: 'C4924A' }))
    }
  }

  if (p.channelPlan?.length) {
    children.push(heading('Channel Plan & Budget'))
    const rows = [new TableRow({ children: ['Channel', 'Role', 'Budget (THB)'].map(h =>
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: h, bold: true })] })] }))
    })]
    for (const c of p.channelPlan) {
      rows.push(new TableRow({ children: [c.channel, c.role, `฿${Number(c.budgetTHB ?? 0).toLocaleString()}`].map(v =>
        new TableCell({ children: [new Paragraph(String(v))] }))
      }))
    }
    children.push(new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows }))
  }

  if (p.timeline?.length) {
    children.push(heading('Timeline'))
    for (const t of p.timeline) {
      children.push(itemTitlePara(`${t.phase} (Day ${t.startOffset}–${t.startOffset + t.durationDays})`))
      children.push(bodyPara((t.activities ?? []).join(' · ')))
    }
  }

  if (p.messagingPillars?.length) {
    children.push(heading('Messaging Pillars'))
    for (const m of p.messagingPillars) {
      children.push(itemTitlePara(m.pillar))
      children.push(bodyPara(m.description))
      children.push(bodyPara(m.proofPoint, { italics: true, color: 'C4924A' }))
    }
  }

  if (p.taglines?.length) {
    children.push(heading('Tagline Options'))
    children.push(bodyPara(p.taglines.join('   •   ')))
  }

  if (p.audiencePersonas?.length) {
    children.push(heading('Audience Personas'))
    for (const a of p.audiencePersonas) {
      children.push(itemTitlePara(a.name))
      children.push(bodyPara(`${a.profile} Motivation: ${a.motivation}`))
      children.push(bodyPara(`Best channel: ${a.bestChannel}`, { italics: true, color: 'C4924A' }))
    }
  }

  if (p.contentCalendar?.length) {
    children.push(heading('Content Calendar'))
    for (const c of p.contentCalendar) {
      children.push(itemTitlePara(`Week ${c.week} — ${c.channel} (${c.contentType})`))
      children.push(bodyPara(c.description))
    }
  }

  if (p.journeyMap?.length) {
    children.push(heading('Customer Journey Map'))
    for (const j of p.journeyMap) {
      children.push(itemTitlePara(`${j.stage} — ${j.touchpoint}`))
      children.push(bodyPara(j.content))
      children.push(bodyPara(`Leakage risk: ${j.leakageRisk}`, { italics: true, color: 'C4924A' }))
    }
  }

  if (p.kpis?.length) {
    children.push(heading('KPIs'))
    for (const k of p.kpis) {
      children.push(itemTitlePara(`${k.metric}: ${k.target}`))
      children.push(bodyPara(k.howToMeasure))
    }
  }

  if (p.preMortem?.length) {
    children.push(heading('Pre-Mortem — What Could Go Wrong'))
    for (const r of p.preMortem) {
      children.push(itemTitlePara(`${r.risk} (${r.likelihood})`))
      children.push(bodyPara(r.mitigation))
    }
  }

  const doc = new DocxDocument({ sections: [{ children }] })
  return Packer.toBuffer(doc)
}
