// Renders a saved Revenue & Marketing Advisor result into a downloadable
// PDF or Word (.docx) file. Built on-demand from the stored `recommendations`
// JSON — never re-generated by AI, never cached as a file — mirrors the
// same pattern as lib/campaign-export.js.
import React from 'react'
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer'
import { Document as DocxDocument, Packer, Paragraph, HeadingLevel, TextRun } from 'docx'

const BRAND_GREEN = '#3B5249'
const BRAND_GOLD = '#C4924A'
const PRIORITY_LABEL = { high: 'HIGH', medium: 'MEDIUM', low: 'LOW' }

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: 'Helvetica' },
  title: { fontSize: 20, marginBottom: 4, color: BRAND_GREEN },
  subtitle: { fontSize: 11, marginBottom: 16, color: '#6B6663' },
  sectionTitle: { fontSize: 13, marginTop: 16, marginBottom: 6, color: BRAND_GREEN, fontWeight: 700 },
  item: { marginBottom: 8, paddingBottom: 8, borderBottom: '1pt solid #E0D9D0' },
  itemTitle: { fontSize: 11, fontWeight: 700, marginBottom: 2 },
  itemBody: { fontSize: 10, color: '#4A4745', lineHeight: 1.4 },
  itemMeta: { fontSize: 9, color: BRAND_GOLD, marginTop: 2 },
})

function InsightSection({ title, items }) {
  return React.createElement(View, null,
    React.createElement(Text, { style: styles.sectionTitle }, title),
    ...(items ?? []).map((ins, i) => React.createElement(View, { key: i, style: styles.item },
      React.createElement(Text, { style: styles.itemTitle }, `[${PRIORITY_LABEL[ins.priority] ?? ins.priority}] ${ins.title}`),
      React.createElement(Text, { style: styles.itemBody }, ins.detail),
      ins.suggestedAction && React.createElement(Text, { style: styles.itemMeta }, `→ ${ins.suggestedAction}`)
    ))
  )
}

function InsightsPdfDocument({ insight }) {
  const rec = insight.recommendations
  return React.createElement(Document, null,
    React.createElement(Page, { size: 'A4', style: styles.page },
      React.createElement(Text, { style: styles.title }, 'Revenue & Marketing Advisor'),
      React.createElement(Text, { style: styles.subtitle }, `${insight.period_start} — ${insight.period_end}`),
      React.createElement(InsightSection, { title: 'Revenue Perspective', items: rec.revenueInsights }),
      React.createElement(InsightSection, { title: 'Marketing Perspective', items: rec.marketingInsights })
    )
  )
}

export async function renderInsightsPdf(insight) {
  return renderToBuffer(React.createElement(InsightsPdfDocument, { insight }))
}

// ── Word (.docx) ────────────────────────────────────────────────────────
function heading(text) {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 120 } })
}
function bodyPara(text, opts = {}) {
  return new Paragraph({ children: [new TextRun({ text, ...opts })], spacing: { after: 100 } })
}
function itemTitlePara(text) {
  return new Paragraph({ children: [new TextRun({ text, bold: true })], spacing: { after: 40 } })
}

export async function renderInsightsDocx(insight) {
  const rec = insight.recommendations
  const children = [
    new Paragraph({ text: 'Revenue & Marketing Advisor', heading: HeadingLevel.TITLE }),
    bodyPara(`${insight.period_start} — ${insight.period_end}`, { color: '6B6663' }),
  ]

  const addSection = (title, items) => {
    children.push(heading(title))
    for (const ins of items ?? []) {
      children.push(itemTitlePara(`[${PRIORITY_LABEL[ins.priority] ?? ins.priority}] ${ins.title}`))
      children.push(bodyPara(ins.detail))
      if (ins.suggestedAction) children.push(bodyPara(`→ ${ins.suggestedAction}`, { italics: true, color: 'C4924A' }))
    }
  }

  addSection('Revenue Perspective', rec.revenueInsights)
  addSection('Marketing Perspective', rec.marketingInsights)

  const doc = new DocxDocument({ sections: [{ children }] })
  return Packer.toBuffer(doc)
}
