// POST /api/bookings — create a confirmed booking
// Rate limit → Turnstile → Zod → availability check → insert → emails

import { createSupabaseAdminClient } from '@/lib/supabase-admin'
import { checkRateLimit, tooManyRequestsResponse } from '@/lib/ratelimit'
import { verifyTurnstile }  from '@/lib/verify-turnstile'
import { bookingSchema }    from '@/lib/schemas'
import { sendEmail, bookingGuestHtml, bookingOwnerHtml } from '@/lib/brevo'
import { findAvailableTherapist } from '@/lib/scheduling'

function addMinutes(time, mins) {
  const [h, m] = time.split(':').map(Number)
  const total = h * 60 + m + mins
  return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`
}

export async function POST(req) {
  const rl = await checkRateLimit(req, 'booking', { limit: 5, window: 600 })
  if (!rl.success) return tooManyRequestsResponse()

  const body = await req.json()

  try { await verifyTurnstile(body.turnstileToken) }
  catch (err) { return Response.json({ error: err.message }, { status: 400 }) }

  const parsed = bookingSchema.safeParse(body)
  if (!parsed.success) {
    return Response.json({ error: parsed.error.issues[0].message }, { status: 400 })
  }
  const d = parsed.data

  const admin = createSupabaseAdminClient()

  // Re-check slot availability (prevents race condition from optimistic UI)
  // and find a qualified, free therapist for this exact window — a slot
  // isn't real availability unless someone can actually staff it.
  const endTime = addMinutes(d.time_slot, d.duration)
  const therapistId = await findAvailableTherapist(admin, {
    treatmentId: d.treatment_id, date: d.date, startTime: d.time_slot, endTime,
  })
  if (!therapistId) {
    return Response.json({ error: 'This slot just filled up. Please choose another time.' }, { status: 409 })
  }

  // Resolve treatment name + price
  const { data: treatment } = await admin
    .from('spa_treatments')
    .select('name, prices')
    .eq('id', d.treatment_id)
    .maybeSingle()

  const price = treatment?.prices?.[String(d.duration)] ?? null

  // Insert booking (ref_code generated by DB trigger)
  const { data: booking, error } = await admin
    .from('bookings')
    .insert({
      guest_name:   d.guest_name,
      guest_email:  d.guest_email || null,
      guest_phone:  d.guest_phone,
      treatment_id: d.treatment_id,
      therapist_id: therapistId,
      date:         d.date,
      time_slot:    d.time_slot,
      duration:     d.duration,
      price,
      source:       'online',
      notes:        d.notes || null,
    })
    .select('ref_code, date, time_slot, duration')
    .single()

  if (error) {
    console.error('[bookings] insert error:', error)
    return Response.json({ error: 'Could not save booking. Please contact us via WhatsApp.' }, { status: 500 })
  }

  const treatmentName = treatment?.name ?? 'Spa Treatment'
  const ownerEmail    = process.env.INQUIRY_EMAIL
  const whatsapp      = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? '66631175211'

  await Promise.allSettled([
    d.guest_email && sendEmail({
      to:      d.guest_email,
      subject: `Booking Confirmed — ${booking.ref_code} — Ton Mai Spa`,
      html:    bookingGuestHtml({
        name:      d.guest_name,
        refCode:   booking.ref_code,
        date:      booking.date,
        time:      booking.time_slot,
        treatment: treatmentName,
        whatsapp,
      }),
    }),
    ownerEmail && sendEmail({
      to:      ownerEmail,
      subject: `New Booking ${booking.ref_code} — ${treatmentName}`,
      html:    bookingOwnerHtml({
        name:      d.guest_name,
        phone:     d.guest_phone,
        refCode:   booking.ref_code,
        date:      booking.date,
        time:      booking.time_slot,
        treatment: treatmentName,
        notes:     d.notes,
      }),
    }),
  ])

  return Response.json({ ok: true, refCode: booking.ref_code })
}
