// POST /api/bookings — create a confirmed booking
// Rate limit → Turnstile → Zod → availability check → insert → emails

import { createSupabaseAdminClient } from '@/lib/supabase-admin'
import { checkRateLimit, tooManyRequestsResponse } from '@/lib/ratelimit'
import { verifyTurnstile }  from '@/lib/verify-turnstile'
import { bookingSchema }    from '@/lib/schemas'
import { sendEmail, bookingGuestHtml, bookingOwnerHtml } from '@/lib/brevo'
import { checkSlotCapacity, capacityErrorFromDb, isPastSlotInSpaTz } from '@/lib/scheduling'
import { upsertCustomer } from '@/lib/customers'

function addMinutes(time, mins) {
  const [h, m] = time.split(':').map(Number)
  const total = h * 60 + m + mins
  return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`
}

export async function POST(req) {
  const rl = await checkRateLimit(req, 'booking', { limit: 5, window: 600 })
  if (!rl.success) return tooManyRequestsResponse()

  const body = await req.json()

  try { await verifyTurnstile(body.turnstileToken) }
  catch (err) { return Response.json({ error: err.message }, { status: 400 }) }

  const parsed = bookingSchema.safeParse(body)
  if (!parsed.success) {
    return Response.json({ error: parsed.error.issues[0].message }, { status: 400 })
  }
  const d = parsed.data

  const admin = createSupabaseAdminClient()

  // The date picker and slot grid already prevent these client-side, but a
  // crafted POST bypasses the UI entirely — Zod only checks FORMAT of
  // date/time/duration, so without these two server-side rules a request
  // could book a slot in the past, or a duration the treatment doesn't
  // offer (which would silently insert with price = NULL).
  if (isPastSlotInSpaTz(d.date, d.time_slot)) {
    return Response.json({ error: 'That time has already passed. Please choose an upcoming slot.' }, { status: 400 })
  }
  const { data: treatment } = await admin
    .from('spa_treatments')
    .select('name, prices, duration_options, is_active')
    .eq('id', d.treatment_id)
    .maybeSingle()
  if (!treatment || treatment.is_active === false) {
    return Response.json({ error: 'This treatment is not available for online booking.' }, { status: 400 })
  }
  if (!(treatment.duration_options ?? []).includes(d.duration)) {
    return Response.json({ error: 'That duration is not offered for this treatment.' }, { status: 400 })
  }

  // Re-check slot availability (prevents race condition from optimistic UI):
  // enough qualified, free therapists for this exact window — some treatments
  // (e.g. a couple's massage) need 2 working simultaneously — AND a free
  // treatment room. A slot isn't real availability unless both hold.
  const endTime = addMinutes(d.time_slot, d.duration)
  const capacity = await checkSlotCapacity(admin, {
    treatmentId: d.treatment_id, date: d.date, startTime: d.time_slot, endTime,
  })
  if (!capacity.ok) {
    return Response.json({ error: 'This slot just filled up. Please choose another time.' }, { status: 409 })
  }
  const therapistIds = capacity.therapistIds

  const price = treatment.prices?.[String(d.duration)] ?? null

  const customerId = await upsertCustomer(admin, { name: d.guest_name, phone: d.guest_phone, email: d.guest_email })

  // Insert booking (ref_code generated by DB trigger)
  const { data: booking, error } = await admin
    .from('bookings')
    .insert({
      guest_name:   d.guest_name,
      guest_email:  d.guest_email || null,
      guest_phone:  d.guest_phone,
      customer_id:  customerId,
      treatment_id: d.treatment_id,
      therapist_id: therapistIds[0],
      secondary_therapist_id: therapistIds[1] ?? null,
      date:         d.date,
      time_slot:    d.time_slot,
      duration:     d.duration,
      price,
      source:       'online',
      notes:        d.notes || null,
    })
    .select('ref_code, date, time_slot, duration')
    .single()

  if (error) {
    // The DB capacity trigger is the atomic backstop for the race window
    // between the checkSlotCapacity pre-check above and this insert — treat
    // a trigger rejection exactly like a failed pre-check, not a server error.
    if (capacityErrorFromDb(error)) {
      return Response.json({ error: 'This slot just filled up. Please choose another time.' }, { status: 409 })
    }
    console.error('[bookings] insert error:', error)
    return Response.json({ error: 'Could not save booking. Please contact us via WhatsApp.' }, { status: 500 })
  }

  const treatmentName = treatment?.name ?? 'Spa Treatment'
  const ownerEmail    = process.env.INQUIRY_EMAIL
  const whatsapp      = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? '66822866058'

  await Promise.allSettled([
    d.guest_email && sendEmail({
      to:      d.guest_email,
      subject: `Booking Received — ${booking.ref_code} — Ton Mai Spa`,
      html:    bookingGuestHtml({
        name:      d.guest_name,
        refCode:   booking.ref_code,
        date:      booking.date,
        time:      booking.time_slot,
        treatment: treatmentName,
        whatsapp,
      }),
    }),
    ownerEmail && sendEmail({
      to:      ownerEmail,
      subject: `New Booking ${booking.ref_code} — ${treatmentName}`,
      html:    bookingOwnerHtml({
        name:      d.guest_name,
        phone:     d.guest_phone,
        refCode:   booking.ref_code,
        date:      booking.date,
        time:      booking.time_slot,
        treatment: treatmentName,
        notes:     d.notes,
      }),
    }),
  ])

  return Response.json({ ok: true, refCode: booking.ref_code })
}
